name: hungroo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: true
  image_path: "assets/images/images.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-BoldCondensed.ttf
    - assets/fonts/Roboto-BlackItalic.ttf
    - assets/fonts/Roboto-Black.ttf
  fonts:
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoBlackItalic
      fonts:
        - asset: assets/fonts/Roboto-BlackItalic.ttf
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
     