name: hungroo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/images.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-BoldCondensed.ttf
    - assets/fonts/Roboto-BlackItalic.ttf
    - assets/fonts/Roboto-Black.ttf
    - assets/images/images.png
    - assets/images/crown.png
    - assets/images/iconss.jpg
    - assets/images/cake.jpg
    - assets/images/german.jpg
    - assets/images/indian.jpg
    - assets/images/italian.jpg
    - assets/images/light.jpg
    - assets/images/quickandeasy.jpg
    - assets/images/filters.png
    - assets/images/recepie.png
    - assets/images/waiting.png
    - assets/images/chef.png
    - assets/images/QRCodes.png
    - assets/images/Profilepage.png
    - assets/images/femalechef.png
    - assets/images/breakfast.webp
    - assets/images/burger.webp
    - assets/images/french.webp
    - assets/images/exotic.webp
  fonts:
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoBlackItalic
      fonts:
        - asset: assets/fonts/Roboto-BlackItalic.ttf
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
     